version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: food-delivery-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sanjay
      POSTGRES_DB: food-delivery
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
